os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - '12'
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CC=gcc-6; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CXX=g++-6; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install vcbuildtools; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm config set msvs_version 2015 --global; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cd test; cd OpenSSL102-choco; choco install OpenSSL102-choco.nuspec; cd ..; cd ..; fi'
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
  - npm install -g homebridge
  - npm install -g homebridge-http-webhooks
  - npm install -g homebridge-sun-position
  - export NODE_GLOBAL_DIR=$(npm root -g)
  - npm install winston@2.3.1
  - 'npm install ioBroker/ioBroker.js-controller#1.5.x --production'
script:
  - node node_modules/mocha/bin/mocha testAdapterWrapperNoInfo.js --exit
  - node node_modules/mocha/bin/mocha testAdapterWrapperWithInfo.js --exit
  - node node_modules/mocha/bin/mocha testAdapterXGlobal.js --exit
  - node node_modules/mocha/bin/mocha testAdapterZLocal.js --exit
  - node node_modules/mocha/bin/mocha testPackageFiles.js --exit
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libavahi-compat-libdnssd-dev
